version: "3.8"
services:
  db:
    image: mysql:8.2
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: 3766
      MYSQL_DATABASE: instabug
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: 3766
      MYSQL_HOST: db
    ports:
      - 3306:3306
  redis:
    image: redis:7.0.0
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - discovery.seed_hosts=["127.0.0.1", "[::1]"]
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      REDIS_URL: redis://redis:6379/1
      SIDEKIQ_WEB_USERNAME: admin
      SIDEKIQ_WEB_PASSWORD: admin
      ELASTICSEARCH_URL: http://elasticsearch:9200

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379/1
      SIDEKIQ_WEB_USERNAME: admin
      SIDEKIQ_WEB_PASSWORD: admin
      ELASTICSEARCH_URL: http://elasticsearch:9200
volumes:
  redis:
